SCRUM-83 ganar terminando mazo de figuras
LavajabonSinRopa/back pull request #34
Opened 2024-11-03 03:05 UTC by ivo-pfaffen

Para testear con el front hay que moverse a la rama SCRUM-65_Completar_figura_propia y cambiar lineas 194, 195 para hacer que se repartan menos cartas.
Modifique tests viejos y agregué uno nuevo que chequea las modificaciones al endpoint (quedó cubierto todo el codigo nuevo de esta PR)

2024-11-03 13:28 UTC, josemochkofsky commented on src/entities/game/game_utils.py
> +        remaining_cards = len(repo.get_player(player_id=player_id)['figure_cards'])
Fijate que en repo.get_player()['figure_cards'] solo están las cartas con estado en 'drawn' (porque es lo que se manda al front). Haciendolo así, si empezas una partida y usas las tres cartas que el jugador tiene en la mano gana, aunque no haya terminado el mazo.

2024-11-03 13:29 UTC, josemochkofsky commented on src/entities/game/game_utils.py
> +        remaining_cards = len(repo.get_player(player_id=player_id)['figure_cards'])
Probablemente, lo mejor sea agregarle un campo 'remaining_cards' a get player y sacar de ahí.

2024-11-03 13:32 UTC, josemochkofsky requested changes
Hay un bug bastante grande: Usar las 3 cartas en la mano de un jugador lo hace ganar.
Recrear: Iniciar partida con el front de la rama SCRUM-65_Completar_figura_propia, completar todas las figuras en la mano de cualquier jugador.

2024-11-03 23:56 UTC, ivo-pfaffen commented
Para evitar pasar datos de más hice un método nuevo (`get_player_figure_cards`) en `gamesRepo.py` que devuelve todas las cartas figura del player. 
Ahora `complete_figure` en `game_utils.py` usa la cantidad de cartas asignadas al player que no estén descartadas (state != "discarded") para calcular las cartas figura que le quedan al jugador.
```py
        # Check if player ran out of cards after discarding
        player_cards = repo.get_player_figure_cards(player_id=player_id)['figure_cards']
        remaining_cards = len([fcard for fcard in player_cards if fcard["state"] != "discarded"])
```

2024-11-03 23:58 UTC, ivo-pfaffen reviewed
Se me re pasó, gracias @josemochkofsky 

Para evitar pasar datos de más hice un método nuevo (`get_player_figure_cards`) en `gamesRepo.py` que devuelve todas las cartas figura del player. 
Ahora `complete_figure` en `game_utils.py` usa la cantidad de cartas asignadas al player que no estén descartadas (state != "discarded") para calcular las cartas figura que le quedan al jugador.
```py
        # Check if player ran out of cards after discarding
        player_cards = repo.get_player_figure_cards(player_id=player_id)['figure_cards']
        remaining_cards = len([fcard for fcard in player_cards if fcard["state"] != "discarded"])
```
Los tests siguen pasando, y agregué 2 para el método nuevo en game_utils.py.

2024-11-04 10:59 UTC, josemochkofsky approved these changes
Ahora sí, todo válido.

2024-11-04 19:52 UTC, merged